DROP TABLE RESULTHORSE;
DROP TABLE BETRATE;
DROP TABLE PROGRAMHORSE;
DROP TABLE HORSE;
DROP TABLE LAHTOTULOKSET;
DROP TABLE LAHTO;
DROP TABLE PROGRAMFILE;
DROP TABLE RESULTFILE;
DROP TABLE GAME;

DROP INDEX resulthorses_idx;

CREATE TABLE PROGRAMFILE (
	FILENAME VARCHAR ( 30 ) NOT NULL,
	LOCALITY VARCHAR ( 20 ) NOT NULL,
	PVM DATE NOT NULL,
	RESULTFILE VARCHAR ( 26 ),
	V1 NUMBER ( 10, 2),
	CONSTRAINT PK_PROGRAMFILE PRIMARY KEY (FILENAME)
	);

CREATE TABLE LAHTO (
	ID VARCHAR ( 25 ) NOT NULL,
	FILENAME VARCHAR ( 30 ) NOT NULL,
	NUMERO NUMBER ( 2, 0 ) NOT NULL,
	LAHTOTAPA VARCHAR ( 20 ) NOT NULL,
	ROTU VARCHAR ( 20 ) NOT NULL,
	MATKA NUMBER ( 4, 0 ) NOT NULL,
	LYHENNE VARCHAR ( 5 ) NOT NULL,
	CONSTRAINT PK_LAHTO PRIMARY KEY (ID),
	CONSTRAINT FK_LAHTO FOREIGN KEY (FILENAME) REFERENCES PROGRAMFILE(FILENAME)
	);

CREATE TABLE LAHTOTULOKSET (
    ID VARCHAR ( 30  ) NOT NULL,
    NUMERO NUMBER ( 2, 0 ) NOT NULL,
    VK1 NUMBER ( 6, 2 ),
    VK2 NUMBER ( 6, 2 ),
    KK1 NUMBER ( 6, 2 ),
    TK1 NUMBER ( 7, 2 ),
    TK2 NUMBER ( 7, 2 ),
	LOPPUAIKA NUMBER ( 4, 1 ),
	PARASAIKA NUMBER ( 4, 1 ),
	NUMERO_1 NUMBER ( 2 ),
	NUMERO_2 NUMBER ( 2 ),
	NUMERO_3 NUMBER ( 2 ),
	CONSTRAINT PK_LAHTOTULOKSET PRIMARY KEY (ID)
	);

CREATE TABLE PROGRAMHORSE (
	LID VARCHAR ( 25 ) NOT NULL,
	TRACKID VARCHAR ( 7 ),
	NUMERO VARCHAR ( 2 ),
	NIMI VARCHAR ( 30 ),
	KULJETTAJA VARCHAR ( 35 ),
	VALMENTAJA VARCHAR ( 35 ),
	MATKA NUMBER ( 4 ),
	RATA NUMBER ( 2 ),
	TASOITUS NUMBER( 3 ) NOT NULL,
	K_S NUMBER ( 5 ) NOT NULL,
	K_1 NUMBER ( 4 ) NOT NULL,
	K_2 NUMBER ( 4 ) NOT NULL,
	K_3 NUMBER ( 4 ) NOT NULL,
	K_R NUMBER ( 10 ) NOT NULL,
	K_PAALU NUMBER ( 4 ),
	K_X NUMBER ( 4 ),
	CONSTRAINT programhorse_tasoitus_check CHECK(TASOITUS >= 0),
	CONSTRAINT PK_PROGRAMHORSE PRIMARY KEY (LID, NUMERO)
	);

CREATE TABLE RESULTFILE (
	FILENAME VARCHAR ( 30 ) NOT NULL,
	LOCALITY VARCHAR ( 20 ) NOT NULL,
	PVM DATE NOT NULL,
	TRACKCONDITION VARCHAR(50),
	CONSTRAINT PK_RESULTFILE PRIMARY KEY (FILENAME)
	);

CREATE TABLE RESULTHORSE (
    PAIKKA NVARCHAR2 ( 3 ) NOT NULL,
	PVM DATE NOT NULL,
	LAHTONUMERO NUMBER ( 2 ) NOT NULL,
	SIJOITUS NUMBER ( 2, 0 ),
	NUMERO NUMBER ( 2, 0 ),
	NIMI VARCHAR ( 30 ),
	LAJI VARCHAR ( 1 ),
	KULJETTAJA VARCHAR ( 40 ),
	AIKA NUMBER ( 4, 1 ),
	LAHTOTYYPPI VARCHAR (10) NOT NULL,
	XCODE VARCHAR ( 10 ),
	X NUMBER ( 1 ),
	KERROIN NUMBER ( 5, 1 ),
	PALKINTO NUMBER ( 7, 0 ),
	MATKA NUMBER ( 4 ) NOT NULL,
	RATA NUMBER ( 2 ) NOT NULL,
	TASOITUS NUMBER ( 3 ) NOT NULL,
	RATA_TUNNISTE VARCHAR ( 6 ),
	VA_1 NUMBER ( 3, 1 ),
	VA_2 NUMBER ( 3, 1 ),
	V500 NUMBER ( 3, 1 ),
	CONSTRAINT tasoitus_check CHECK(TASOITUS >= 0),
	CONSTRAINT PK_RESULTHORSE PRIMARY KEY (NIMI, LAJI, PVM, LAHTONUMERO)
	);
	CREATE INDEX resulthorses_idx ON resulthorse(PVM, LAHTONUMERO, PAIKKA);


CREATE TABLE GAME (
	TITLE VARCHAR ( 30 ) NOT NULL,
	COUNT NUMBER ( 6 ) NOT NULL,
	HITS NUMBER ( 6 ) NOT NULL,
	WINNINGS NUMBER ( 8, 2 ) NOT NULL,
	LOSSES NUMBER ( 8, 2 ) NOT NULL,
	HORSES NUMBER ( 10, 2 ),
	CONSTRAINT PK_GAME PRIMARY KEY (TITLE)
	);

commit;


