use hippos;

ALTER TABLE resulthorse DROP INDEX resulthorse_nimi_idx;

DROP TABLE IF EXISTS LAHTO;
DROP TABLE IF EXISTS PROGRAMFILE;
DROP TABLE IF EXISTS LAHTOTULOKSET;
DROP TABLE IF EXISTS PROGRAMHORSE;
DROP TABLE IF EXISTS RESULTFILE;
DROP TABLE IF EXISTS RESULTHORSE;
DROP TABLE IF EXISTS GAME;

CREATE TABLE PROGRAMFILE (
	FILENAME VARCHAR ( 30 ) NOT NULL,
	LOCALITY VARCHAR ( 20 ) NOT NULL,
	PVM DATE NOT NULL,
	RESULTFILE VARCHAR ( 26 ),
	V1 DECIMAL ( 10, 2),
	PRIMARY KEY (FILENAME)
	);

CREATE TABLE LAHTO (
	ID VARCHAR ( 25 ) NOT NULL,
	FILENAME VARCHAR ( 30 ) NOT NULL,
	NUMERO DECIMAL ( 2, 0 ) NOT NULL,
	LAHTOTAPA VARCHAR ( 20 ) NOT NULL,
	ROTU VARCHAR ( 20 ) NOT NULL,
	MATKA DECIMAL ( 4, 0 ) NOT NULL,
	LYHENNE VARCHAR ( 5 ) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_LAHTO FOREIGN KEY (FILENAME) REFERENCES PROGRAMFILE(FILENAME)
	);

CREATE TABLE LAHTOTULOKSET (
    ID VARCHAR ( 30  ) NOT NULL,
    NUMERO DECIMAL ( 2, 0 ) NOT NULL,
    VK1 DECIMAL ( 6, 2 ),
    VK2 DECIMAL ( 6, 2 ),
    KK1 DECIMAL ( 6, 2 ),
    TK1 DECIMAL ( 7, 2 ),
    TK2 DECIMAL ( 7, 2 ),
	LOPPUAIKA DECIMAL ( 4, 1 ),
	PARASAIKA DECIMAL ( 4, 1 ),
	NUMERO_1 DECIMAL ( 2 ),
	NUMERO_2 DECIMAL ( 2 ),
	NUMERO_3 DECIMAL ( 2 ),
	PRIMARY KEY (ID)
	);

CREATE TABLE PROGRAMHORSE (
	LID VARCHAR ( 25 ) NOT NULL,
	TRACKID VARCHAR ( 7 ),
	NUMERO VARCHAR ( 2 ),
	NIMI VARCHAR ( 30 ),
	KULJETTAJA VARCHAR ( 35 ),
	VALMENTAJA VARCHAR ( 35 ),
	MATKA DECIMAL ( 4 ),
	RATA DECIMAL ( 2 ),
	TASOITUS DECIMAL( 3 ) NOT NULL,
	YHT_S DECIMAL ( 3 ) NOT NULL,
	XCODE DECIMAL ( 3 ) NOT NULL,
	KCODE DECIMAL ( 3 ) NOT NULL,
	YHT_1 DECIMAL ( 3 ) NOT NULL,
	YHT_2 DECIMAL ( 3 ) NOT NULL,
	YHT_3 DECIMAL ( 3 ) NOT NULL,
	YHT_R DECIMAL ( 10 ) NOT NULL,
	V_S DECIMAL ( 3 ) NOT NULL,
	V_1 DECIMAL ( 3 ) NOT NULL,
	V_2 DECIMAL ( 3 ) NOT NULL,
	V_3 DECIMAL ( 3 ) NOT NULL,
	V_R DECIMAL ( 10 ) NOT NULL,
	K_S DECIMAL ( 5 ) NOT NULL,
	K_1 DECIMAL ( 4 ) NOT NULL,
	K_2 DECIMAL ( 4 ) NOT NULL,
	K_3 DECIMAL ( 4 ) NOT NULL,
	K_R DECIMAL ( 10 ) NOT NULL,
	K_PAALU DECIMAL ( 4 ),
	SUBSTART_1 VARCHAR (50),
	SUBSTART_2 VARCHAR (50),
	SUBSTART_3 VARCHAR (50),
	SUBSTART_4 VARCHAR (50),
	SUBSTART_5 VARCHAR (50),
	SUBSTART_6 VARCHAR (50),
	SUBSTART_7 VARCHAR (50),
	SUBSTART_8 VARCHAR (50),
	CONSTRAINT programhorse_tasoitus_check CHECK(TASOITUS >= 0),
	PRIMARY KEY (LID, NUMERO)
	);

CREATE TABLE RESULTFILE (
	FILENAME VARCHAR ( 30 ) NOT NULL,
	LOCALITY VARCHAR ( 20 ) NOT NULL,
	PVM DATE NOT NULL,
	TRACKCONDITION VARCHAR(50),
	PRIMARY KEY (FILENAME)
	);

CREATE TABLE RESULTHORSE (
	PVM DATE NOT NULL,
	LAHTONUMERO DECIMAL ( 2 ) NOT NULL,
	SIJOITUS DECIMAL ( 2, 0 ),
	NUMERO DECIMAL ( 2, 0 ),
	NIMI VARCHAR ( 30 ),
	LAJI VARCHAR ( 1 ),
	KULJETTAJA VARCHAR ( 40 ),
	AIKA DECIMAL ( 4, 1 ),
	LAHTOTYYPPI VARCHAR (10) NOT NULL,
	XCODE VARCHAR ( 10 ),
	X DECIMAL ( 1 ),
	KERROIN DECIMAL ( 5, 1 ),
	PALKINTO DECIMAL ( 7, 0 ),
	MATKA DECIMAL ( 4 ) NOT NULL,
	RATA DECIMAL ( 2 ) NOT NULL,
	TASOITUS DECIMAL ( 3 ) NOT NULL,
	RATA_TUNNISTE VARCHAR ( 6 ),
	VA_1 DECIMAL ( 3, 1 ),
	VA_2 DECIMAL ( 3, 1 ),
	V500 DECIMAL ( 3, 1 ),
	CONSTRAINT tasoitus_check CHECK(TASOITUS >= 0),
	PRIMARY KEY (NIMI, LAJI, PVM, LAHTONUMERO)
	);
	CREATE INDEX resulthorse_nimi_idx on resulthorse(nimi);


CREATE TABLE GAME (
	TITLE VARCHAR ( 30 ) NOT NULL,
	COUNT DECIMAL ( 6 ) NOT NULL,
	HITS DECIMAL ( 6 ) NOT NULL,
	WINNINGS DECIMAL ( 8, 2 ) NOT NULL,
	LOSSES DECIMAL ( 8, 2 ) NOT NULL,
	HORSES DECIMAL ( 10, 2 ),
	PRIMARY KEY (TITLE)
	);

commit;

